server:
  port: 9002
spring:
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB #最大请求文件的大小
      max-file-size: 20MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  #数据源基本信息
  datasource:
    druid:
      username: ${DB_USERNAME:U_PORTAL}
      password: ${DB_PASSWORD:U_PORTAL@12345}
      url: jdbc:mysql://${DB_HOST:81.70.244.63}:${DB_PORT:3306}/PORTAL_DB?useSSl=ture&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      #连接池属性
      initial-size: 50
      max-active: 100
      min-idle: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 1000
      keep-alive: true
      remove-abandoned: true
      remove-abandoned-timeout: 180
      log-abandoned: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      maxOpenPreparedStatements: 100
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

  redis:
    #数据库索引
    database: ${REDIS_DB:2}
    host: ${REDIS_HOST:81.70.205.68}
    port: ${REDIS_PORT:16379}
    password: ${REDIS_PWD:zfj@026418}
    #连接超时时间
    timeout: 50000000
    
mybatis:
  mapper-locations: classpath*:com/jeelp/platform/**/*Mapper.xml
  type-aliases-package: com.jeelp.platform.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql                           #分页插件方言选择
  reasonable: true                               #合理化参数，设为true时pageNum<=0 时会查第一页， pageNum>pages（超过总数时），会查询最后一页
  support-methods-arguments: true
  params: count=countSql

# IP 本地解析
ip:
  local-parsing: true
    
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000

  

